### ISSUE TITLE
2 Issues in one

### ISSUE THREAD

**Issue by Sensire** [CuppaZee/CuppaZee#10]
Hi Friends,

1. The Android V1 App is still crashing. Even after 4 Weeks in the Play Store for Android it has no update. We are two persons with two Samsung Galaxy S7 and the app does not work anymore. Will there a V2 in the next future?
2. While browsing through my Profile f.e. "https://cuppazee.app/user/Kerzenwelt/captures/normal" i miss the entry/icon for the golden clover leaf. It only shows "Virtual Shamrock" and "Clover Leaf" but not the "Golden Clover Leaf"

Thanks for this fine tool/site/app.

**Comment by sohcah** [comment]
CuppaZee V2 released about a month ago. Could you confirm for me whether you are running V1.2 or V2.0.5 please? You can find this by holding on the app on your home screen, and then pressing "App Info", or going to Settings > Apps > CuppaZee.

I hadn't found the icon for the Golden Clover Leaf yet... but thanks to your link I've managed to get it, so will get that out in the next patch.

**Comment by Sensire** [comment]
Hi at first. Did'nt managed it to answer just in time. But today i am back and can give you some more informations. We are using V2.0.5 as offered in the play store. We have deinstalled and reinstalled and the same error since weeks.

I have made 3 snapshots to show you the problem:

 



 

I hope this will help for further investigations

 

Regards

 

 

Von: Sam Hindess ***@***.***> 
Gesendet: Montag, 19. April 2021 13:44
An: CuppaZee/CuppaZee ***@***.***>
Cc: Sensire ***@***.***>; Author ***@***.***>
Betreff: Re: [CuppaZee/CuppaZee] 2 Issues in one (#10)

 

CuppaZee V2 released about a month ago. Could you confirm for me whether you are running V1.2 or V2.0.5 please? You can find this by holding on the app on your home screen, and then pressing "App Info", or going to Settings > Apps > CuppaZee.

I hadn't found the icon for the Golden Clover Leaf yet... but thanks to your link I've managed to get it, so will get that out in the next patch.

**Comment by sohcah** [comment]
Sorry, looks like those attachments didn't get copied over to Github. Could you send them via email to me at admin@cuppazee.app?

**Comment by sohcah** [comment]
This should be resolved with the V2.1 release.
