### ISSUE TITLE
German Translation.

### ISSUE THREAD

**Issue by Sensire** [CuppaZee/CuppaZee#11]
Hi Sam,

is there an easy way to give some translated stuff over to this project? I'm using the german version and found some misspelled or even not translated words. Btw. this app is so helpful and ful of useful information. The Planners are crazy and additionally the "still missing munzees" hunt fills up many weekends ;)

Regards

**Comment by Megachip** [comment]
Hi @Sensire,

just check https://github.com/CuppaZee/CuppaZee/blob/main/translations/files/de.json and provide a pull request for sam ...

**Comment by sohcah** [comment]
Please do not manually edit the JSON files. Translations are edited through an external tool.
If you'd like to join the translation team, please DM me on Messenger at https://m.me/samuel.hindess/
