### ISSUE TITLE
Add a way to pick a more accurate location on Nearby Bouncers on Web

### ISSUE THREAD

**Issue by mirabilos** [CuppaZee/CuppaZee#12]
On a normal laptop webbrowser, https://max.cuppazee.app/bouncers/nearby does not work. This seems to be intended for mobile devices with location, with no way to set the location manually.

**Comment by sohcah** [comment]
Hi, I'm going to need some more details here. What Web Browser are you using, and on what OS?

**Comment by mirabilos** [comment]
Firefox 78.12.0esr on Debian bullseye/amd64.

But this is not the problem.

The problem is that it asks for location permission, gets it denied (because the laptop has no location **anyway**), and then refuses to work.

**Comment by sohcah** [comment]
If you deny access to your location, of course it won't work.
It can't get your location if you don't allow it, and so can't figure out what's "nearby".

Please accept access to your location for it to work.

**Comment by mirabilos** [comment]
Sam Hindess dixit:

>If you deny access to your location, of course it won't work.
>It can't get your location if you don't allow it, and so can't figure out what's "nearby".

THAT IS NOT THE PROBLEM.

The browser DOES NOT have a location because the laptop DOES NOT
have the MERE *CONCEPT* of a location BECAUSE IT DOES NOT FUCKING
HAVE A GPS CHIP OR ANYTHING.

>Please accept access to your location for it to work.

I cannot BECAUSE THERE IS NO SUCH THING AS A LOCATION on a normal
desktop or laptop system.

Write your code so that one can set the desires location manually
as alternative. It’s not THAT hard. I’ve done so.

bye,
//mirabilos
-- 
Gestern Nacht ist mein IRC-Netzwerk explodiert. Ich hatte nicht damit
gerechnet, darum bin ich blutverschmiert… wer konnte ahnen, daß SIE so
reagier’n… gestern Nacht ist mein IRC-Netzwerk explodiert~~~
	(as of 2021-06-15 The MirOS Project temporarily reconvenes on OFTC)

**Comment by sohcah** [comment]
You could have quite easily and calmly clarified that this was not a bug report but a feature request (a way to pick a more accurate location on Web) without swearing at me.

It works fine on Web, just giving an inaccurate location, assuming you allow location access.
I will happily work to add a way to pick a more precise location on Web, but you made this seem like a bug report, not a feature request.

**Comment by sohcah** [comment]
<img width="1191" alt="Screenshot 2021-08-06 at 09 11 20" src="https://user-images.githubusercontent.com/51970078/128478908-6e234580-bc6c-44cf-a1e5-6c7dc9cdef49.png">

I've now implemented a new marker that you can drag to get a more accurate location, along with a "Move Location Here" button which you can use alongside "Search" to move to a location further away! 😀

Hope this helps,
Sam

**Comment by sohcah** [comment]
Update: I've improved it further, so that using the "Search" tool automatically changes your location.

**Comment by sohcah** [comment]
Resolved in today's update :)
