### ISSUE TITLE
Negative Scores 

### ISSUE THREAD

**Issue by Megachip** [CuppaZee/CuppaZee#57]
**Describe the bug**
Negative Scores are shown as positive

**Screenshots**
![3D4B46FA-BFCE-4F81-A4BC-73F0E24B636D](https://user-images.githubusercontent.com/487352/88450814-0e40f680-ce52-11ea-8ed4-4fa9df54f9c9.jpeg)
should be -5

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2020
 - OS: iOS 13.6
 - Version 210

**Comment by sohcah** [comment]
Not an issue. You got -5 points for the capture and +10 points for the cap-on as you captured your own munzee... CuppaZee merges cap and cap-on points if you capture your own munzee, so they -5 and +10 got added to make +5. :)
