### ISSUE TITLE
Unable to access Quebec Quest Progress

### ISSUE THREAD

**Issue by Technical-13** [CuppaZee/CuppaZee#65]
**Describe the bug**
Unable to access Quebec Quest Progress

**To Reproduce**
1. Click `>` next to "Quebec Quest Progress" with 5 or more users added.
2. See change in user

**Expected behavior**
Clicking `>` next to "Quebec Quest Progress" should open the progress for the Quebec Quest

**YouTube Video**
[![CuppaZee bug (user selection bug)](http://img.youtube.com/vi/e4pqf8eX22A/0.jpg)](https://youtu.be/e4pqf8eX22A "CuppaZee bug (user selection bug)")

**Desktop (please complete the following information):**
 - OS: Windows 7 (NT 6.1)
 - Browser: Firefox
 - Version: 80.0
- UA: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0

**Additional context**
Seems to be a z-index bug because it selects the user that would be there if the user menu in the bottom corner was open.

**Comment by sohcah** [comment]
The Quebec Quest is not running at the moment, so the button is disabled.

**Comment by sohcah** [comment]
Additionally, you do not need to click the arrow to access something.

Finally, this is a bug in a dependency of CuppaZee, not in CuppaZee itself. It will be fixed when I get time to update that dependency. https://github.com/callstack/react-native-paper/pull/1845

**Comment by Technical-13** [comment]
Same issue when I click under the POI Challenge.

**Comment by sohcah** [comment]
> Same issue when I click under the POI Challenge.

Can you show me a video of this, please?

**Comment by Technical-13** [comment]
Looks like it fixed itself when you disabled the link for The Quebec Quest.

**Comment by sohcah** [comment]
> Looks like it fixed itself when you disabled the link for The Quebec Quest.

It has been disabled for a couple of weeks.
