### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by JonnyTech** [CuppaZee/CuppaZee#66]
How do I prevent others fron viewing my profile? I notice that some users have blocked their activity but I cannot find the setting to do it myself.

**Comment by sohcah** [comment]
There is currently no way to do this, sorry.

**Comment by JonnyTech** [comment]
Ah, ok, then why do many players show a red triangle?

![cz](https://user-images.githubusercontent.com/3584732/91372596-f15e6100-e80b-11ea-9105-5ed16efc8582.png)
