### ISSUE TITLE
Clicking on a clan user shows my own page on desktop (mobile ok)

### ISSUE THREAD

**Issue by mirabilos** [CuppaZee/CuppaZee#78]
**Describe the bug**

I cannot see a user’s profile from the clan list.

**To Reproduce**

1. Go to 'Clan Stats'
2. Click on one of the usernames in the leftmost column of the table
3. The URL changes to `https://cuppazee.app/user/<their name>` shortly before being redirected to `https://cuppazee.app/user/<my name>`

**Expected behavior**

I see the user page of that user.

This works on iOS but not on a Linux desktop Firefox.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux
 - Browser Firefox
 - Version 78.3.0esr

**Smartphone (please complete the following information):**
 - Device: iPhone SE 2016
 - OS: iOS 13
 - Browser using the Äpp

**Additional context**

None, but ask me if needed.

I *was* trying to figure out who from my clan was PEAR and who was PINE. This is very cumbersome on iOS, especially as CuppaZee does not do tabbed browsing.

**Comment by sohcah** [comment]
Please turn off Firefox's Enhanced Tracking Protection.

Although CuppaZee doesn't track you, Firefox is pretty heavy on it's tracking protection, and occasionally gets false positives, which seem to be the case here. I suggest you report the issue to Mozilla.

**Comment by mirabilos** [comment]
After turning EPT off, the problem persists.

**Comment by mirabilos** [comment]
Sam Hindess dixit:

>Please turn off Firefox's Enhanced Tracking Protection.

This still happens, even with that turned off.
