### ISSUE TITLE
Very poor performance with v2 on Android

### ISSUE THREAD

**Issue by JonnyTech** [CuppaZee/CuppaZee#9]
On my Android phone, v1 would load very quickly, ie initial app load in a few seconds, and similar when changing pages.

But with v2 it takes over 30 seconds just to get past the logo and maybe display the what's new page. Buttons are unresponsive or laggy, I usually end up pressing them multiple times then the app may wake up and try to process all the presses and lag even more.

Navigating and page loading is painful with the delays and the app - or even indeed the whole phone - becomes unresponsive to the point that I have to hold the power button down to restart the phone. So I do just a few page changes then force quit and restart the app to do more.

Is there anything that can be done? I suspect that it is because my phone has only 1Gb RAM. I tend to force quit all other apps before using v2 but that only mildly helps. Other apps may occasionally slow down but CuppaZee in consistent in this.

Running v2.0.5 on AOSP 9 (LineageOS without GApps) on ARM 32bit device with 1Gb RAM.

**Comment by sohcah** [comment]
I really need a bit more information (preferably, a video of some of the issues).
I've done a lot of testing myself over the past few weeks on the few android devices I have available to me and haven't been able to reproduce this issue in any form, so it's basically impossible for me to fix without a lot more info.

**Comment by JonnyTech** [comment]
Video is difficult because if any other apps are running they usually cause issues with cuppazee and both run out or memory - I do not have another device to record it externally. Does the app generate any logs that I can send you?
